{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentteams-java.serviceAccountName" . }}
{{- end }}
{{- if .Values.controlPlane.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentteams-java.controlPlaneServiceAccountName" . }}
{{- end }}
