{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentteams-java.operatorServiceAccountName" . }}
{{- end }}
{{- if .Values.gateway.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentteams-java.gatewayServiceAccountName" . }}
{{- end }}
{{- if .Values.controlPlane.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentteams-java.controlPlaneServiceAccountName" . }}
{{- end }}
