#!/usr/bin/env bash
set -euo pipefail

# Register one development Agent and connect it to the local QwenPaw runtime.
# The Agent UUID is generated by the Control Plane and injected into the Worker
# manifest at apply time; the Operator then injects AGENTTEAMS_AGENT_ID into
# the Pod; the tracked example keeps its placeholder UUID.

ROOT=$(cd "$(dirname "$0")/.." && pwd)
NAMESPACE=${AGENTTEAMS_NAMESPACE:-agentteams}
CONTROL_PLANE_SERVICE=${AGENTTEAMS_CONTROL_PLANE_SERVICE:-agentteams-agentteams-java-control-plane}
WORKER_NAME=${AGENTTEAMS_WORKER_NAME:-qwenpaw-worker}
AGENT_NAME=${AGENTTEAMS_WORKER_AGENT_NAME:-qwenpaw-kind-worker}
IDEMPOTENCY_KEY=${AGENTTEAMS_WORKER_IDEMPOTENCY_KEY:-qwenpaw-kind-worker-v1}
LOCAL_PORT=${AGENTTEAMS_CONTROL_PLANE_LOCAL_PORT:-18080}

source "$ROOT/deploy/dev-env.sh"

for command_name in curl jq kubectl; do
  command -v "$command_name" >/dev/null || {
    echo "缺少 ${command_name}，请先安装。" >&2
    exit 1
  }
done

agent_id=""
if kubectl -n "$NAMESPACE" get worker "$WORKER_NAME" >/dev/null 2>&1; then
  agent_id=$(kubectl -n "$NAMESPACE" get worker "$WORKER_NAME" -o jsonpath='{.spec.agentId}')
  [[ "$agent_id" != "" ]] || {
    echo "已有 Worker ${WORKER_NAME} 但 spec.agentId 为空，拒绝覆盖。" >&2
    exit 1
  }
  echo "复用已有 QwenPaw Worker Agent ${agent_id}"
else
  port_forward_log=$(mktemp -t agentteams-control-plane-port-forward.XXXXXX)
  kubectl -n "$NAMESPACE" port-forward "service/${CONTROL_PLANE_SERVICE}" \
    "${LOCAL_PORT}:8080" >"$port_forward_log" 2>&1 &
  port_forward_pid=$!
  cleanup() {
    kill "$port_forward_pid" 2>/dev/null || true
    wait "$port_forward_pid" 2>/dev/null || true
    rm -f "$port_forward_log"
  }
  trap cleanup EXIT

  until curl -fsS "http://127.0.0.1:${LOCAL_PORT}/actuator/health" >/dev/null; do
    if ! kill -0 "$port_forward_pid" 2>/dev/null; then
      echo "Control Plane port-forward 失败：$(sed -n '1,5p' "$port_forward_log")" >&2
      exit 1
    fi
    sleep 2
  done

  response=$(curl -fsS -X POST "http://127.0.0.1:${LOCAL_PORT}/api/v1/agents" \
    -H "Idempotency-Key: ${IDEMPOTENCY_KEY}" \
    -H 'Content-Type: application/json' \
    -d "{\"name\":\"${AGENT_NAME}\",\"runtime\":\"qwenpaw\",\"capabilities\":{\"qwenpaw\":\"true\",\"java\":\"17\"}}")
  agent_id=$(jq -er '.id' <<<"$response")
  [[ "$agent_id" != "00000000-0000-0000-0000-000000000001" ]] || {
    echo "Control Plane 返回了占位 Agent UUID，拒绝部署。" >&2
    exit 1
  }
  echo "已注册 QwenPaw Worker Agent ${agent_id}"
fi

sed "s/00000000-0000-0000-0000-000000000001/${agent_id}/g" \
  "$ROOT/deploy/examples/qwenpaw-worker.yaml" | kubectl apply -f -

deployment_deadline=$((SECONDS + 180))
until kubectl -n "$NAMESPACE" get deployment "$WORKER_NAME" >/dev/null 2>&1; do
  if (( SECONDS >= deployment_deadline )); then
    echo "Operator 未在 180 秒内创建 Worker Deployment ${WORKER_NAME}。" >&2
    exit 1
  fi
  sleep 2
done
kubectl -n "$NAMESPACE" wait --for=condition=available \
  "deployment/${WORKER_NAME}" --timeout=180s
kubectl -n "$NAMESPACE" wait --for=jsonpath='{.status.phase}'=Ready \
  "worker/${WORKER_NAME}" --timeout=180s

echo "QwenPaw Worker 已连接：agent=${agent_id} deployment=${WORKER_NAME}"
